version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: .docker/dev-env.Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev